# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neoforge_version=21.1.248
neoforge_version_range=[21.1.0,)
loader_version_range=[4,)

## Mappings
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Mod Properties
mod_id=biofactory
mod_name=Bio-Factory
mod_license=MIT
mod_version=0.6.0
mod_group_id=com.github.elenterius.biofactory
mod_vendor=Elenterius
mod_authors=Elenterius
mod_credits=
mod_description=Bio-Factory is a addon mod for Biomancy X Create
mod_url=https://www.curseforge.com/minecraft/mc-mods/biofactory-port
mod_issue_url=https://github.com/Mackery6969/Bio-Factory/issues
mod_update_url=https://raw.githubusercontent.com/Mackery6969/Bio-Factory/refs/heads/mc1.21.1/neoforge/updates.json

## Dependencies

### Biomancy Mod
biomancy_version=2.9.8.1
biomancy_version_range=[2.9.8,)

### "Create" Mod
create_version=6.0.11-300
create_version_range=[6.0.11,6.1.0)
ponder_version=1.0.87+mc1.21.1
flywheel_version=1.0.6

### Geckolib Mod
geckolib_version=4.9.2
geckolib_version_range=[4.9,)
